### ISSUE TITLE
Computation requirements?

### ISSUE THREAD

**Issue by varshiths** [samarth-robo/contactdb_prediction#1]
Hello!
I think your work is very interesting. The paper is well written too!
However, the paper does not have details regarding the CPU, GPU and memory requirements for training the models.
Could you expand on that briefly or point me to the details if I missed it by any chance?
(Judging by the size of the batch and code, do you use a Titan X? How much memory does the batch exactly consume?)
Thank in advance. :)

**Comment by samarth-robo** [comment]
Thank you, @varshiths . I don't have the exact memory numbers right now, but in general the VoxNet models required more memory to train than the PointNet models. And yes, we used a Titan X.
