### ISSUE TITLE
ConnectionRefusedError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by yuweijiang** [samarth-robo/contactdb_prediction#2]
Hi, I try to train the model by using the bash as follow:
python train_val.py \
        --data_dir /scratch/grasp_data/meshes_data \
        --instruction handoff \
        --checkpoint_dir checkpoints \
        --config_file configs/pointnet.ini \
        --device_id 0,1,2,3
While I meet the error about the connection resufed, I have no idea. Did I miss something? I have no idea, could you help me?
The error report is shown:
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /env/main (Caused by NewConnectionError('<u
rllib3.connection.HTTPConnection object at 0x7f574e887fd0>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by samarth-robo** [comment]
Hi @yuweijiang , that is because of [`visdom`](https://github.com/facebookresearch/visdom). The training code pushes logging data to the visdom server. In a separate terminal, start the visdom server:
```
$ source activate contactdb_prediction
$ visdom
```

**Comment by yuweijiang** [comment]
Yes, the problem is solved. Thank you so much!
