### ISSUE TITLE
How to preprocess the data

### ISSUE THREAD

**Issue by stevenlsw** [samarth-robo/contactdb_prediction#3]
Hi, 

thanks for your interesting work. I have a question about how to get the preprocessed data, as you provided in the link, Is there any kinds of scripts for doing this ? Especially about how to transform an arbitrary mesh model to the voxel input ? thanks.

**Comment by samarth-robo** [comment]
Hi @stevenlsw , those scripts are in the `analysis` branch: https://github.com/samarth-robo/contactdb_prediction/tree/analysis. See the section on "Preprocessing Data" in the README of that branch. You will find the scripts and code there. Let me know if you have further questions.

**Comment by stevenlsw** [comment]
thanks so much. That helps a lot. I will close the issue.
